### ISSUE TITLE
返却される元号が実際の存在期間と一致しない

### ISSUE THREAD

**Issue by muratagawa** [pldb/zakuro#3]
[粟津の戦い \- Wikipedia](https://ja.wikipedia.org/wiki/%E7%B2%9F%E6%B4%A5%E3%81%AE%E6%88%A6%E3%81%84)

> 粟津の戦い（あわづのたたかい）は、寿永3年1月20日（1184年3月4日）に近江国粟津にて行われた源義仲と源頼朝派遣の東国諸将との間の戦い。

木曽義仲が死んだとされる「寿永3年1月20日（1184年3月4日）」の日付を zakuro に渡してみましたが、返ってくる元号が上記の日付と異なっていました。

テストしたスクリプトは以下の内容です。

```ruby
require 'zakuro'

western_date = Date.new(1184, 3, 4)

merchant = Zakuro::Merchant.new(condition: { date: western_date })
puts merchant.commit.to_json
```

返却値は以下。

```json
{
   "year":{
      "first_gengou":{
         "name":"元暦",
         "number":1
      },
      "second_gengou":{
         "name":"",
         "number":-1
      },
      "zodiac_name":"甲辰",
      "total_days":354
   },
   "month":{
      "number":1,
      "leaped":false,
      "days_name":"小",
      "first_day":{
         "number":1,
         "zodiac_name":"辛卯",
         "remainder":"27-1226",
         "western_date":"1184-02-14"
      },
      "odd_solar_terms":[
         {
            "index":5,
            "remainder":"43-3478"
         }
      ],
      "even_solar_terms":[
         {
            "index":4,
            "remainder":"28-1642"
         }
      ]
   },
   "day":{
      "number":20,
      "zodiac_name":"庚戌",
      "remainder":"46-1226",
      "western_date":"1184-03-04"
   }
```

「元暦（げんりゃく）」は後鳥羽天皇の頃に1184～1185年の間だけ存在した暦のようですが、1184年3月4日は含まれていないようです。

[元暦\(ゲンリャク\)とは \- コトバンク](https://kotobank.jp/word/%E5%85%83%E6%9A%A6-493287)

> 平安末期、後鳥羽天皇の時の年号。1184年4月16日～1185年8月14日。

これを踏まえると、`first_gengou` の戻り値は「元暦1年」ではなく「寿永3年」になるのが正しいはずです。

これは zakuro の変換結果が間違っているのでしょうか？それとも Wikipedia などの解説サイトが間違っていますか？

**Comment by muratagawa** [comment]
ちなみに『平家物語』原文では、「[寿永](https://ja.wikipedia.org/wiki/%E5%AF%BF%E6%B0%B8)」は「壽永」、「[元暦](https://ja.wikipedia.org/wiki/%E5%85%83%E6%9A%A6)」は「元曆」という旧字体で書かれていました。Wikipedia の年号のページにも書いてます。
そんなマニアックな部分まで zakuro でサポートする必要あるとは思えませんが。バージョン 10.0 ぐらいで対応してください。

**Comment by pldb** [comment]
ご指摘ありがとうございます。
結論としてはライブラリの仕様部分の不具合で、実用性を考えた時には改修が必要です。

* 寿永3年1月20日が元暦3年1月20日に変換されるのは、『日本暦日原典』の通りです
* 『日本暦日原典』では年ごとに元号を与えており、実際の施行日の年月日まで追跡できません
* 寿永3年4月16日（ユリウス暦1184年5月27日）に改元されており、4月15日までは寿永、4月16日からは元暦です

[日本の暦日データベース](https://eco.mtk.nao.ac.jp/cgi-bin/koyomi/caldb.cgi) では改元を年月日まで考慮しています。
従って、今後は下記方針で対応する予定です。

* 改元の根拠となる資料を決め、それを元に年月日ベースの改元処理を行うようにします
* 現行の改元処理は残し、年月日ベースの改元処理結果と併記します

根本に関わる処理のため時間を要します。旧字体の件も含め、解決までしばらくお待ちください。

**Comment by muratagawa** [comment]
![OK](https://media.giphy.com/media/sWWYgKVkOlL0c/giphy.gif)

**Comment by pldb** [comment]
対応完了しました。
前回のコメントから対応を一部変更しております。
> * 改元の根拠となる資料を決め、それを元に年月日ベースの改元処理を行うようにします
> * 現行の改元処理は残し、年月日ベースの改元処理結果と併記します

全て『日本史年表』に準拠し、現行の改元処理は残しても混乱するだけなので削除します。

**Comment by muratagawa** [comment]
zakuro-0.0.2 にて、「西暦1184年3月4日」が「寿永3年」と変換されることを確認しました。お疲れサントス。

ただ、寿永から元暦に改元された「西暦1184年4月16日」の日付を渡しても、「元暦1年」ではなく「寿永3年」が返ってきました。まだバグってませんか？

テストコード:

```test.rb
require 'zakuro'

western_date = Date.new(1184, 4, 16)
merchant = Zakuro::Merchant.new(condition: { date: western_date })
puts merchant.commit.to_json
```

返却値:

```json
{"year":{"first_gengou":{"name":"寿永","number":3},"second_gengou":{"name":"","number":-1},"zodiac_name":"甲辰","total_days":354},"month":{"number":3,"leaped":false,"days_name":"小","first_day":{"number":1,"zodiac_name":"庚寅","remainder":"26-7145","western_date":"1184-04-13"},"odd_solar_terms":[{"index":9,"remainder":"44-2420"}],"even_solar_terms":[{"index":8,"remainder":"29-585"}]},"day":{"number":4,"zodiac_name":"癸巳","remainder":"29-7145","western_date":"1184-04-16"}}
```

**Comment by pldb** [comment]
ご指摘ありがとうございます。
まずは状況を確認してみます。

**Comment by muratagawa** [comment]
元号の切り替わりの境界値テストを、全部の元号でやる必要があると思います。現状では `spec/zakuro/era/japan_spec.rb` の中で一部の元号だけテストされてるみたいですが。

以下はテストのデータセット例と擬似コードです。

データセットの例:

```yaml
# gentou_test_data.yml
---
- gengou: 大化
  start_at: 645-07-17
- gengou: 白雉
  start_at: 650-03-22
- gengou: 朱鳥
  start_at: 686-08-14
```

テストの擬似コード:

```ruby:japan_spec.rb
dataset = YAML.load_file('gentou_test_data.yml')

dataset.each do |set|
  date = Zakuro::Western::Calendar.new(set.start_at)
  item = Zakuro::Japan::GengouResource.first_line(date: date)
  expect(item.name).to eq(set.gengou)
end
```

**Comment by pldb** [comment]
元号の境界値チェック、コードありがとうございます。
実は `spec/zakuro/version/senmyou/summary/specifier_spec.rb` で元号含めた境界値チェックをしていました。
（バグりそうなところ限定ですが）
ご指摘の通り、 `japan_spec.rb` でもやっていたので、そちらで集中的にチェックしたほうが良かったですね。すっかり忘れていました。

**Comment by pldb** [comment]
それで、不具合かどうかですが、結論、不具合ではなさそうです。
`西暦1184年4月16日` は寿永3年で問題ないです。元暦1年の境界値は `1184-5-27` です。
（境界値は `doc/gengou.md` に一覧表記しています）
おそらく、和暦日が `元暦4月16日` なので、そちらと混同されている可能性を感じています。
もしやと思い暦日データベースでも調べましたが、やはり上記の通りであることを確認しました。

**Comment by pldb** [comment]
いずれにせよ、全部の元号でチェックしたほうが良いのは同意です。
最低限、チェック用のテストケースは作成したいと思います。

**Comment by muratagawa** [comment]
[元暦とは \- コトバンク](https://kotobank.jp/word/%E5%85%83%E6%9A%A6-493287) を参考に改元日を入力したんですが、このサイトの記述が非常に紛らわしいですね。西暦と和暦が区別せずに書かれています。というか、普通に読んだらどれも西暦1184年4月16日が元暦への改元日です。

> 元暦（読み）ゲンリャク
>
> デジタル大辞泉の解説
> 平安末期、後鳥羽天皇の時の年号。1184年4月16日～1185年8月14日。
>
> 大辞林 第三版の解説
> 年号（1184.4.16～1185.8.14）。寿永の後、文治の前。後鳥羽天皇の代。
>
>
> 日本の元号がわかる事典の解説
> 日本の元号（年号）。1184年（寿永3）4月16日改元。
> 
> 精選版 日本国語大辞典の解説
> 平安末期、後鳥羽天皇の代の年号。寿永三年（一一八四）四月一六日代始により改元。

zakuro の挙動が正しいことは理解しました。辞書の大半が誤解を招く記述になっているのも理解できました。

このやり場のない怒りを、どうかクローズしてください。

**Comment by pldb** [comment]
非常に分かりづらい表記ですね。
それとも、「西暦年mm月dd日」のうち、「mm月dd日」は和暦日にする慣例でもあるんでしょうか。仮にそうであったにせよ、直感的な表記とは言いづらいです。

**Comment by pldb** [comment]
テストケースの作成完了に伴いクローズします
